server:
  port : 8081

---

spring:
  config:
    activate:
      on-profile: dev

server:
  port : 8081

  datasource:
    driver-class-name : org.postgresql.Driver
    url : jdbc:postgresql://localhost:5432/user-subscription
    username : postgres
    password : root
